export const EVENT_MENU_DIALOG_ADD = 'EVENT_MENU_DIALOG_ADD'
export const EVENT_MENU_DIALOG_EDIT = 'EVENT_MENU_DIALOG_EDIT'

export const EVENT_MENU_CHANGE = 'EVENT_MENU_CHANGE'

export const EVENT_CONTENT_CLEAR = 'EVENT_CONTENT_CLEAR'
export const EVENT_CONTENT_RESET = 'EVENT_CONTENT_RESET'
export const EVENT_CONTENT_ADD = 'EVENT_CONTENT_ADD'
export const EVENT_CONTENT_CHANGE = 'EVENT_CONTENT_CHANGE'
